#!/usr/bin/env bash

set -o errexit -o pipefail -o noclobber -o nounset

. utils.sh
. args.sh
. s3.sh
. s3api.sh
. sts.sh

get_args "$@"

if [[ -n "${_arg_profile}" ]]; then
  assume_role
fi

case "${_arg_command}" in
  s3)
    s3
    ;;
  s3api)
    s3api
    ;;
  sts)
    sts
    ;;
  help)
    print_long_help
    exit 0
    ;;
  *)
    _PRINT_HELP=yes die "$0: error: argument command: Invalid choice, valid choices are:

s3"
    ;;
esac
