#!/usr/bin/env bash

# poor man's release script

filename=$1

head -4 aws-micro > "${filename}"
{ cat args.sh;
  cat s3.sh;
  cat s3api.sh;
  cat sts.sh;
  cat utils.sh;
  tail -n +10 aws-micro;
} >> "${filename}"
chmod 755 "${filename}"
